all: 
	make -C Dom2Cond
	make -C Frac2Floor
	make -C Maxima2Cint
	make -C Maxima2Cfloat
	make -C Maxima2MPC
	make -C Pourcent2Mod
	make -C FloorCeilExtract

clean:
	make -C Dom2Cond clean
	make -C Frac2Floor clean
	make -C Maxima2Cint clean
	make -C Maxima2Cfloat clean
	make -C Maxima2MPC clean
	make -C Pourcent2Mod clean
	make -C FloorCeilExtract clean
